!classDefinition: #Persona1 category: 'Clase1-SegundaActividad'!
DenotativeObject subclass: #Persona1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Clase1-SegundaActividad'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Persona1 class' category: 'Clase1-SegundaActividad'!
Persona1 class
	instanceVariableNames: ''!

!Persona1 class methodsFor: 'saludo' stamp: 'VLC 8/14/2023 20:09:14'!
comoEstas
	^'bien'! !

!Persona1 class methodsFor: 'saludo' stamp: 'VLC 8/14/2023 20:04:01'!
hola
	^'chau'! !
